name: appcbm-db

version: '3.7'
services:
  pg:
    container_name: appcbm-db
    image: bitnami/postgresql:latest
    ports:
      - '5444:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=appcbm